export const routes = {
  home: '/',
  episodes: '/episodes',
  episode: (id: string) => `/episodes/${id}`,
  characters: '/characters',
  character: (slug: string) => `/characters/${slug}`,
  bestiary: '/bestiary',
  monster: (slug: string) => `/bestiary/${slug}`,
  armory: '/armory',
  map: '/map',
  quotes: '/quotes',
  soundtrack: '/soundtrack',
  interactive: '/interactive',
  quiz: '/interactive/quiz',
  guessEpisode: '/interactive/guess-episode',
  tracker: '/interactive/tracker',
  submitStory: '/interactive/submit-story',
  community: '/community',
  forum: '/forum',
  thread: (id: string) => `/forum/${id}`,
  login: '/login',
  register: '/register',
  news: '/news',
  newsItem: (slug: string) => `/news/${slug}`,
  easterEggs: '/easter-eggs',
  about: '/about',
} as const;

export const mainNav = [
  { label: 'Серии', href: routes.episodes },
  { label: 'Персонажи', href: routes.characters },
  { label: 'Бестиарий', href: routes.bestiary },
  { label: 'Оружейная', href: routes.armory },
  { label: 'Карта', href: routes.map },
  { label: 'Цитаты', href: routes.quotes },
  { label: 'Саундтрек', href: routes.soundtrack },
  { label: 'Интерактив', href: routes.interactive },
  { label: 'Комьюнити', href: routes.community },
];
